### PR TITLE
remove  localhost reference in transition.mdx

### PR DESCRIPTION
**Pull request by eerkmen**
Clean up doc links #536 issue fixed in transition.mdx file

### CODE REVIEW

**Comment by DefinitelyMaybe** [comment]
nice! thank you @eerkmen ! Have a look around the other pages too, if you're using vscode [find and replace](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options) can help track them down easily

**Comment by eerkmen** [comment]
Oh sorry for not being clearer @DefinitelyMaybe , I already checked other instances of localhost with advanced search option in VSC. There is only one reference of localhost in the project folder(which was the one you pointed out on the issue page)

**Comment by grischaerbe** [comment]
Good catch! 👍 
Thanks a lot, high appreciated ❤️

**Comment by DefinitelyMaybe** [comment]
Oh man! I'm happily surprised 😅 thank you for clearing that up! I guess I was simply the unlucky person for finding it haha

**Pull request merged**
