### PR TITLE
useTrail prototype

### PR DESCRIPTION
**Pull request by grischaerbe**
Port of https://github.com/pmndrs/drei#usetrail

### CODE REVIEW

**Comment by grischaerbe** [comment]
Preview: https://threlte-lnumcg2fs-threlte.vercel.app/extras/use-trail

**Comment by jerzakm** [comment]
Fun component. I think that a different example would work better to show off what this does.  Right now it waits for user input before it's visible what it does. What if we changed the example to a cube travelling in a sinusoidal pattern.
- Cube's x += time
- Cube's y += Math.sin(time)
- Move camera x+= time like cube so that the cube appears to be in place

image

**Comment by jerzakm** [comment]
Do we still plan to add it? I started prototyping something similar and then I remembered about this PR.

**Comment by jerzakm** [comment]
Closing because it's really old. If anyone works on this they should make a fresh PR probably anyway.

**Pull request closed without merging**
