### PR TITLE
Added collapsible categories in docs.

### PR DESCRIPTION
**Pull request by chocola-mint**
Addresses issue #123 (Collapsible categories in docs) by injecting code that modifies KitDocs' sidebar, using Svelte's onMount lifecycle callback. The [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) HTML element is used to minimize the code needed to implement the change.

As KitDocs doesn't include any classes or ids to identify sidebar categories, the resulting solution ended up being very hacky. I've left comments documenting my implementation, though.

Here is a demonstration:
demo

### CODE REVIEW

**Comment by grischaerbe** [comment]
Hi @chocola-mint and thanks for your PR! It looks like a good approach. I somehow think it would make more sense to have the packages collapsed or have the collapsed subcategories occupy way less vertical space, or even both?

**Comment by chocola-mint** [comment]
> Hi @chocola-mint and thanks for your PR! It looks like a good approach. I somehow think it would make more sense to have the packages collapsed or have the collapsed subcategories occupy way less vertical space, or even both?

Sounds like a good idea. Here's how it looks now:
demo

**Comment by grischaerbe** [comment]
Hey @chocola-mint, can you try a version where only the top-level packages are collapsed and maybe "@threlte/core" is expanded by default?

**Comment by chocola-mint** [comment]
> Hey @chocola-mint, can you try a version where only the top-level packages are collapsed and maybe "@threlte/core" is expanded by default?

Here it is:
demo

**Comment by grischaerbe** [comment]
Closed due to deprecated docs

**Pull request closed without merging**
