### PR TITLE
Astro transitions DOM & Listeners leak

### PR DESCRIPTION
**Pull request by jerzakm**
We're having issues with a potential memory leak - if you navigate in the docs several times (especially on an intensive route like /extras examples) - the amount of DOM nodes and JS listeners jumps up drastically.

It seems that Svelte components and listeners aren't destroyed. I thought it'd get fixed by this PR but I doesn't help our case
https://github.com/withastro/astro/pull/8264

image

I created this PR to anchor the docs in time. The fastest way to reproduce is to click through the sidebar of [Extras](https://threlte-fs391o5z6-threlte.vercel.app/docs/reference/extras/getting-started)

### CODE REVIEW

**Comment by jerzakm** [comment]
Fixed & release by Astro
https://github.com/withastro/astro/pull/8448

**Comment by grischaerbe** [comment]
Thanks ✌️

**Comment by grischaerbe** [comment]
Is this "ready for review"?

**Comment by jerzakm** [comment]
Copy from discord: 
The astro PR fixed it locally on my PC, but our github preview is still leaking like it did before. I tested both dev and build+preview.

Could it be an issue with vercel build now?

**Comment by matthewp** [comment]
I'm on the Astro core team and am going to be looking into this for you.

**Comment by jerzakm** [comment]
View transitions still bugged, I'll close this to clean up our PR list. Maybe we can revisit in the future.

**Pull request closed without merging**
