### PR TITLE
Camera-Controls update

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
expand that pane! previously it was stuck on false

### CODE REVIEW

**Comment by kitschpatrol** [comment]
Hey! I'm the author of Svelte Tweakpane UI and I've noticed this issue in some of the Threlte examples.

It came up on my end in an [issue here](https://github.com/kitschpatrol/svelte-tweakpane-ui/issues/4) a while back, and I found that I can't handle the case of passing a  boolean literal directly to the prop without permanently "locking" the expand / collapse state of certain pane types.

If you want a pane to be initially collapsed but still be user-openable...

Instead of this:
```svelte
<script lang="ts">
	import { Pane } from 'svelte-tweakpane-ui';
</script>

<Pane expanded={false}>
```

Do this:
```svelte
<script lang="ts">
	import { Pane } from 'svelte-tweakpane-ui';
	let expanded = false;
</script>

<Pane bind:expanded>
```

Not thrilled to require a work-around, but can't dig further at the moment.

**Comment by kitschpatrol** [comment]
Actually I can open a quick PR to fix this everywhere.

**Comment by kitschpatrol** [comment]
I think I caught them all here:
https://github.com/threlte/threlte/pull/1121

**Comment by DefinitelyMaybe** [comment]
closing in favor of #1121

**Pull request closed without merging**
