### PR TITLE
Docs nav enhancements

### PR DESCRIPTION
**Pull request by ixxie**
Some steps to make the docs navigation more user-friendly:

1. Add aliases to menu items and adjust styling and order
2. Shrink the search 'input' into a single icon (less deceptive, less space)
3. Reorganize tutorials and move first tutorial to that section
4. Experiment with reorganization of extra

WIP and I'm not entirely happy with all of it yet, but I feel like its going somewhere. Especially the organization of extras is challenging.

### CODE REVIEW

**Comment by edsunman** [comment]
Thanks for looking at organising the extras sidebar! 

I like what you have done with the collapsible categories. Here is my suggestion for how to organise them. It's sort of halfway between the current layout and your new version. I think it's neater to keep hooks etc separate and then add subcategories to the components.


https://github.com/threlte/threlte/assets/14927523/e379a413-229c-43c8-a7ba-4f4d02225cf1

**Comment by DefinitelyMaybe** [comment]
@edsunman nice!  seems pretty organized for the extras sidebar 👍 

It can be a tricky challenge. To show the breadth of options, I made a [starlight docs variation](https://blahblah-sigma.vercel.app/) but extras still feels a bit un-organized in it.

still not sure where we're going with the docs just yet 🤷‍♂️ 

The ideas are marinating😄

**Comment by michealparks** [comment]
I really like @edsunman's organization suggestion for extras (I'm also a bit biased, I really like how drei organizes extras, which is similar).

**Comment by DefinitelyMaybe** [comment]
Omgosh! I just noticed! GitHub has the same UI problem as us, they've gone with making a collapsed down `...` UI component

Screenshot_2024-03-17-17-22-57-53_e4424258c8b8649f6e67d283a50a2cbc

Might be confusing if we end up with a burger icon and a triple dot icon, but it works 😅

**Comment by ixxie** [comment]
Thanks @edsunman, this is exactly the input I was hoping for since I had no idea on how to organize this! When I get around to it, I'm gonna try and pick up @DefinitelyMaybe's starlight branch and integrate this stuff with it.

**Comment by edsunman** [comment]
I've opened a new pull request for the sidebar categories: https://github.com/threlte/threlte/pull/912

It can either be merged on it's own or added along with other docs changes - or just ignored completely 😂

**Pull request closed without merging**
