### PR TITLE
Remove tailwind classes from examples

### PR DESCRIPTION
**Pull request by flo-bit**
Removed most tailwind classes from the examples.

Only example I found that I left as-is for now that still has tailwind classes is extras/transitions, as that uses a few more classes for a custom button, which maybe should be switched to tweakpane instead?

### CODE REVIEW

**Review by DefinitelyMaybe — APPROVED** [review]
Love this! ❤️ 

I don't think the docs needs to worry about changeset tho, lemme double check with team, I could be wrong 😅

**Comment by michealparks** [comment]
No changset needed for docs since it's not versioned / shipped to NPM 😁

**Comment by michealparks** [comment]
One last note: we're soon going to enforce prettier for all PRs to pass, @flo-bit csn you run "pnpm run format" on all your open PRs at the root level of the monorepo?

**Comment by michealparks** [comment]
@flo-bit I've just added prettier to our CI checks. You'll have to do the following to clear up issues, let me know if you have problems!

* Merge latest main into your branches
* Run `pnpm i` to upgrade prettier
* Run `pnpm format` from the root `threlte` repo
* Prettier check should be green after push to origin 🎉

**Comment by flo-bit** [comment]
> @flo-bit I've just added prettier to our CI checks. You'll have to do the following to clear up issues, let me know if you have problems!
> 
> * Merge latest main into your branches
> * Run `pnpm i` to upgrade prettier
> * Run `pnpm format` from the root `threlte` repo
> * Prettier check should be green after push to origin 🎉

All good from my side 👍

**Pull request merged**
