### PR TITLE
v6: Move <Instance> and <InstancedMesh> to extras

### PR DESCRIPTION
**Pull request by jpaquim**

### CODE REVIEW

**Comment by grischaerbe** [comment]
Hey @jpaquim, is this PR still active? Otherwise I'm giving it a shot. I looked into r3fs/dreis implementation of this and [they found a pretty nice solution](https://github.com/pmndrs/drei/blob/6b402d91c196c15be65c4405853c7f267a6285bb/src/core/Instances.tsx#L57-L83) to the interactivity problem, maybe we can look into porting and merging parts of that?

**Comment by jpaquim** [comment]
@grischaerbe I just rebased this one, hope I didn't introduce any issue while solving the conflicts.

**Comment by grischaerbe** [comment]
Hey @jpaquim, great that you're on it! There seems to be an error with the InstancedMesh still:
```
@threlte/docs-next:build:  error   "Three" is not exported by "../../packages/core/src/lib/index.ts", imported by "../../packages/extras/src/lib/components/InstancedMesh/InstancedMesh.svelte".
```
I guess you need to adapt to the new single `<T>` component syntax, then we're good?

**Comment by grischaerbe** [comment]
I'm not sure if you can look into the build logs, currently it's failing because of this error:

```
@threlte/docs-next:build:  error   "InstancedMesh" is not exported by "../../packages/core/src/lib/index.ts", imported by "src/examples/core/instanced-mesh-simple/Scene.svelte".
```

**Comment by grischaerbe** [comment]
I refactored the implementation in #359

**Pull request closed without merging**
