### PR TITLE
Next theatre docs

### PR DESCRIPTION
**Pull request by ixxie**
WIP pull request for adding `@threlte/theatre` to `docs-next`.

- [x] transform legacy `.md` files to the new `.mdx` format
- [x] fix issues with `<Editable>`'s  example *
  - [x] studio UI overlays the docs interface
  - [ ] ~stackblitz for the example is broken~ (non-blocking)
- [x] add component signatures
- [x] review and extend linking to the the `theatre-js` docs
- [x] clarify the studio workflow in `getting-started` and other sections

\* I could use advice on these points @grischaerbe . It seems we are running into a similar issue as I raised with `<BasicVehicleController>`:

image

In this case, however, the studio UI is essential to the example, as I am not sure how to proceed. Additionally, the StackBlitz link is broken, getting the following error, which I also ran into last week when trying to create a Threlte example in StackBlitz:

```
$ vite
Forced re-optimization of dependencies

  VITE v4.2.1  ready in 9461 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
21:58:52 [vite-plugin-svelte] prebundle libraries in progress ...
✘ [ERROR] Could not resolve "three/examples/jsm/objects/GroundProjectedEnv"

    node_modules/@threlte/extras/dist/components/Environment/GroundProjectedEnv.svelte:13:35:
      13 │ ...ojectedEnv } from 'three/examples/jsm/objects/GroundProjectedEnv';
         ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./examples/jsm/objects/GroundProjectedEnv" was not found on the file system:

    node_modules/three/package.json:14:24:
      14 │     "./examples/jsm/*": "./examples/jsm/*",
         ╵                         ~~~~~~~~~~~~~~~~~~

  You can mark the path "three/examples/jsm/objects/GroundProjectedEnv" as external to exclude it from the bundle, which will remove this error.

21:59:00 [vite-plugin-svelte] prebundle libraries done.
package                 files    time      avg
@threlte/core              42   1.94s   46.2ms
@threlte/extras            10   1.03s    0.10s
@threlte/theatre            6   0.48s   80.4ms
Error: Build failed with 1 error:
node_modules/@threlte/extras/dist/components/Environment/GroundProjectedEnv.svelte:13:35: ERROR: Could not resolve "three/examples/jsm/objects/GroundProjectedEnv"
    at failureErrorWithLog (/home/projects/kyncse--run/node_modules/esbuild/lib/main.js:1626:15)
    at buildResponseToResult/< (/home/projects/kyncse--run/node_modules/esbuild/lib/main.js:1038:44)
    at runOnEndCallbacks/< (/home/projects/kyncse--run/node_modules/esbuild/lib/main.js:1502:13) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Could not resolve "three/examples/jsm/objects/GroundProjectedEnv"'
    }
  ],
  warnings: []
}
```

### CODE REVIEW

**Comment by ixxie** [comment]
I suppose that the 'examples/*@reset.svelte` files can be left out from the new docs?

**Comment by ixxie** [comment]
It seems I have no way to reviewing the failed deployment logs?

**Comment by ixxie** [comment]
Since `<Editable>` has some of those magic props like `<T>` I am a little uncertain still about the component signature.

Note also I separated `<Theatre>` from the other components because it is conceptually less essential.

**Comment by grischaerbe** [comment]
Thanks so much, this is awesome! ❤️

**Pull request merged**
