### PR TITLE
Collapsible sidebar

### PR DESCRIPTION
**Pull request by DefinitelyMaybe**
using session storage :)

### CODE REVIEW

**Comment by grischaerbe** [comment]
Cool, looks good! Can we also persist the scroll pos of the sidebar in that fashion? If you want to add that to this PR I can wait with merging, otherwise I'll merge it right away. Your call! ❤️

**Comment by DefinitelyMaybe** [comment]
can take a look into it but would perf a separate PR

**Comment by DefinitelyMaybe** [comment]
quick update: have noticed the id updates without a svelte mount/destory. Will update the code to sort this out. one moment

**Comment by grischaerbe** [comment]
Thanks a lot @DefinitelyMaybe! ❤️

**Pull request merged**
