### PR TITLE
Fix: Update and Reorganize CONTRIBUTING.md (towards #502)

### LINKED ISSUE #502: Update Contributor Docs

### PR DESCRIPTION
**Pull request by eerkmen**
This PR addresses issue #502 and includes the following changes:

1. Reorganization of the 'Ways to Contribute' and 'Contributing Workflow' sections.
2. Addition of a section to describe GitHub labels and their significance.
3. Enhanced explanations for 'Commit Convention'.
4. Clarification on the usage of changesets.

By making these updates, we aim to provide a clearer and more informative guide for contributors.

@ixxie, as you self-assigned this issue, your review and feedback would be highly valuable.

### CODE REVIEW

**Comment by ixxie** [comment]
Thanks for the PR @eerkmen!

I like the direction you are taking with organizing the document coherently.

The Threlte maintainer team has just been having it's first official meetings in the last week's; up until recently this has mostly been mainly @grischaerbe of course. So there are a bunch of developments that need to also be added to this which - of course - you couldn't have known about.

So here is what I will do: I'm going to merge your PR since the syntactic improvements are very good; but I'm going to keep the issue open because we still need to make some more changes. Then, in the coming days, I'm going to draft a new PR, and I'm going to ping as well as the maintainer team for comments and reviews.

Thanks again for the good work!

**Review by ixxie — CHANGES_REQUESTED** [review]
Thanks for the PR @eerkmen!

I like the direction you are taking with organizing the document coherently.

The Threlte maintainer team has just been having it's first official meetings in the last week's; up until recently this has mostly been mainly @grischaerbe of course. So there are a bunch of developments that need to also be added to this which - of course - you couldn't have known about.

So here is what I will do: I'm going to merge your PR since the syntactic improvements are very good; but I'm going to keep the issue open because we still need to make some more changes. Then, in the coming days, I'm going to draft a new PR, and I'm going to ping as well as the maintainer team for comments and reviews.

But, there is one thing missing - and it's very ironic considering the content of the PR - a changeset! Please add one and I will happily merge. 

Thanks again for the good work!

**Comment by eerkmen** [comment]
Thank you for your kind words, @ixxie!

I'm thrilled to hear that the Threlte maintainer team has been having official meetings and that there are new developments on the horizon. It's great that the project is evolving, and I'm excited to contribute further as it grows.

I see the irony in missing a changeset for a PR about changesets—definitely a face-palm moment on my end! I've gone ahead and added the changeset detailing the improvements made in this PR.

Thanks again for considering my contribution!

**Review by ixxie — CHANGES_REQUESTED** [review]
@eerkmen I still don't see a changeset here; did you forget to commit it?

**Review by ixxie — APPROVED** [review]

**Pull request merged**
