### PR TITLE
Threlte v6

### PR DESCRIPTION
**Pull request by grischaerbe**
# Threlte v6

__[Open this PR in Codeflow](https://pr.new/https://github.com/threlte/threlte/pull/272)__

This PR tracks progress on Threlte v6:

- Convert all packages to Threlte's new render components.
- Plugin API
- Advanced Rendering Pipeline / Frame Loop
- New Interaction System
- `useLoader` refactoring
- New Documentation
- Color Management
- Merging `<Three>` and `<T>` to `<T>` without the use of a preprocessor
- (Get rid of the preprocessor)
- Basic `<Suspense>` component

This branch (`next`) will be published with the tag `next`, e.g.: `npm i @threlte/core@next`.

## Render Components Conversion

This includes the following per component:
- When converting:
  - Use Threlte *Render Components* instead of *Wrapper Components*
  - Separate the component types into a new file placed next to the component itself. Example: Component: Grid.svelte, Types: Grid.svelte.d.ts
  - Remove the component types everywhere else
  - Remove the component type export from the respective `index.ts`
  - Adapt docs (unsure how at the moment)
  
- When removing:
  - Remove the component
  - Remove the component types
  - Remove the exports from the respective `index.ts`

## `@threlte/extras`

- [x] GLTF
- [x] Text
- [x] Edges (#230)
- [x] HTML
- [x] Float (#227)
- [x] ContactShadows
- [x] Disposables
- [x] Environment
- [x] Grid

## `@threlte/rapier`

- [x] World
- [x] RigidBody
- [x] Collider
- [x] AutoColliders
- [x] CollisionGroups
- [x] Attractor
- [x] Debug

## Adapted to v5 types

- [x] TransformableObject

## Moved to `@threlte/extras` and converted

- [X] AudioListener (#248)
- [X] Audio (#248)
- [X] PositionalAudio (#248)
- [x] OrbitControls
- [x] TransformControls
- [x] InstancedMesh (#245)
- [x] Instance (#245)
- [x] Layers (will use the Plugin API)

## Deleted

- [x] SpotLight
- [x] OrthographicCamera
- [x] PerspectiveCamera (#239)
- [x] PositionalAudioHelper (#244)
- [x] AmbientLight
- [x] DirectionalLight
- [x] PointLight
- [x] HemisphereLight
- [x] Fog
- [x] FogExp2
- [x] Mesh
- [x] Group (#241)
- [x] Object3D (#243)
- [x] Line
- [x] Line2
- [x] LineSegments
- [x] MeshInstance
- [x] Object3DInstance
- [x] LightInstance
- [x] CameraInstance (#246)
- [x] LineInstance
- [x] Pass (until a better solution is found)

## Plugin API

- [X] Threlte Plugin API (#273)

## Event System

- [x] Threlte v6 Interactivity Plugin (#298)

## `useLoader` refactoring

- [x] `useLoader` refactoring (#290)

## Advanced Rendering Pipeline / Frame Loop

- [X] Advanced Rendering Pipeline API (#258)

## Documentation

- [X] Intro Page Desktop (#276)
- [X] Intro Page Mobile (#277)
- [x] Docs Layout Desktop (#276)
- [X] Docs Layout Mobile (#277)
- [x] Showcase Desktop (#283)
- [x] Showcase Mobile (#283)
- [x] Writing documentation

## Merging `<Three>` and `<T>` to `<T>` without the use of a preprocessor

- [x] Merging `<Three>` and `<T>` to `<T>` without the use of a preprocessor (#296)

## Color Management

- [X] Adapt color mangement API of Three.js

Suggestions made by @donmccurdy:
- Prop names for color props: `<Canvas colorSpace={"srgb"} toneMapping={ACESFilmicToneMapping} />`
- `THREE.ColorManagement.enabled = true` >= Three.js r150, `THREE.ColorManagement.legacyMode = false` < Three.js r150
[Current default values for Three.js and preferred default values as well as default values set by R3F](https://docs.google.com/spreadsheets/d/1Gv2SToWQSmsGfsp4V-Kh59nxAHMZqIJQ3QYMXvHhZ7s/edit?usp=sharing).

### CODE REVIEW

**Comment by janosh** [comment]
Sorry to bug but is there an ETA for v6?

**Comment by ixxie** [comment]
Deprecated

**Comment by grischaerbe** [comment]
@ixxie Why deprecated? Threlte 6 != Theatre 6 🫠

**Comment by ixxie** [comment]
> @ixxie Why deprecated? Threlte 6 != Theatre 6 🫠

Whooops sorry, brain was broken!

**Pull request merged**
