### PR TITLE
Docs responsiveness - Intro page

### PR DESCRIPTION
**Pull request by jerzakm**
WIP, pr for build checks

- less bad landing - Feature section flex col to row md: viewport

### CODE REVIEW

**Comment by jerzakm** [comment]
chrome_XoV4UTKooD
chrome_wHdwMLxidz

**Comment by jerzakm** [comment]
chrome_BqIj5B6pZo
chrome_uIYuTiMwbj

**Comment by grischaerbe** [comment]
> Before chrome_uIYuTiMwbj After chrome_BqIj5B6pZo
> 
> I still don't like it. Idk. Code feels out of place

Ah sorry, I should've mentioned the code will probably go and @AlexWarnes Stackblitz starter will be linked, what do you think of that?

**Comment by jerzakm** [comment]
chrome_nbrz8HNay9
chrome_0dGSU7YjdG
chrome_mYzc7tZDbV
chrome_ZnxObKhcTX

**Comment by jerzakm** [comment]
> > …
> > I still don't like it. Idk. Code feels out of place
> 
> Ah sorry, I should've mentioned the install code will probably go and @AlexWarnes Stackblitz starter will be linked, what do you think of that?

Sounds good. Stackblitz button will look better and be more functional than just npm install code.

**Pull request merged**
