### PR TITLE
[next] HTML component

### PR DESCRIPTION
**Pull request by michealparks**
### Overview

This PR 
* migrates the `<HTML>` component to runes mode.
* adds the partial occlusion features that the drei counterpart has.

### CODE REVIEW

**Comment by clibequilibrium** [comment]
Hi @michealparks do you think it's trivial to port this occlusion logic to current main branch without Svelte 5?

**Comment by michealparks** [comment]
Back-porting this to Svelte 4 shouldn't be too hard. The hard part is getting this working as changes to @threlte/core and the `<Canvas>` component will likely be required. If people are still using Svelte 4 / Threlte 7 when this gets finished then I'll be happy to back port.

**Comment by michealparks** [comment]
html3

Occlusion added

**Comment by clibequilibrium** [comment]
> html3 [ html3 ](https://private-user-images.githubusercontent.com/3834780/330559527-6ba82b1f-ed7e-4c30-aea0-4baf01562604.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTQyNzUsIm5iZiI6MTcxNTcxMzk3NSwicGF0aCI6Ii8zODM0NzgwLzMzMDU1OTUyNy02YmE4MmIxZi1lZDdlLTRjMzAtYWVhMC00YmFmMDE1NjI2MDQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTkxMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZjY2NhYTdhMmQ2ZWZlNWY5ODIxNTE5MzQzYWMwODg4NzBiZTEwODY5NWIyM2FiYzZiOTI2MmMwNGE5N2I0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TKQvVNciDk0F7aVe2QvsskhF4J0Wgajy01CiptdMDnQ) [ ](https://private-user-images.githubusercontent.com/3834780/330559527-6ba82b1f-ed7e-4c30-aea0-4baf01562604.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MTQyNzUsIm5iZiI6MTcxNTcxMzk3NSwicGF0aCI6Ii8zODM0NzgwLzMzMDU1OTUyNy02YmE4MmIxZi1lZDdlLTRjMzAtYWVhMC00YmFmMDE1NjI2MDQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTRUMTkxMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZjY2NhYTdhMmQ2ZWZlNWY5ODIxNTE5MzQzYWMwODg4NzBiZTEwODY5NWIyM2FiYzZiOTI2MmMwNGE5N2I0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TKQvVNciDk0F7aVe2QvsskhF4J0Wgajy01CiptdMDnQ)
> 
> Occlusion added

This is awesome !

**Comment by clibequilibrium** [comment]
@michealparks  just ported it to Svelte 4 ! A question for you, it seems that TransformControls and Raycast won't be working ? So it's either HTML component gets event or Canvas. Do you happen to have a workaround ?

I know TransformControls can be attached to a different DOMElement but it doesn't seem to work

**Comment by clibequilibrium** [comment]
```ts
const logVertex = `
#include <common>
#include <logdepthbuf_pars_vertex>
void main() {
    gl_Position = projectionMatrix * modelViewMatrix * vec4( position, 1.0 );
    #include <logdepthbuf_vertex>
}
`;

const logFragment = `
#include <logdepthbuf_pars_fragment>

void main() {

	#include <logdepthbuf_fragment>
	gl_FragColor = vec4(0.0,0.0,0.0,0.0);
	
}
`;
```

Those shaders are needed to be applied to ``T.ShaderMaterial`` to support ``logarithmicDepthBuffer ``

```ts
<T.ShaderMaterial side={DoubleSide} vertexShader={logVertex} fragmentShader={logFragment} />
```

Based on https://discourse.threejs.org/t/shadermaterial-render-order-with-logarithmicdepthbuffer-is-wrong/49221/3 
image

**Comment by michealparks** [comment]
Thanks for raising the `logarithmicDepthBuffer` issue, I'll try to add that to this PR today!

> I should mention it's YouTube video embed.

Yeah, this component definitely comes with performance caveats, especially if you're embedding another site where you cannot control performance whatsoever.

**Comment by clibequilibrium** [comment]
> Thanks for raising the `logarithmicDepthBuffer` issue, I'll try to add that to this PR today!
> 
> > I should mention it's YouTube video embed.
> 
> Yeah, this component definitely comes with performance caveats, especially if you're embedding another site where you cannot control performance whatsoever.

Thanks ! Could I have your opinion on something? 

I have orbit controls and fly camera, but when the user goes very close to the HTML component there is a chance they won't be able to zoom out because the HTML component takes majority of the screen not allowing user to pass any inputs (not scroll not pinch out zoom). 

Do you think it would be handy to have a function that would try to calculate not only the distance between HTML and camera but also consider the screen space size of the object ? 

Having this would allow to disable HTML interactivity if the camera is very very close to the component. Otherwise current UX is that once the user goes very close to HTML - they can't zoom out any longer and move at all.

**Comment by clibequilibrium** [comment]
For anyone looking for Svelte 4 port please check out this PR (not perfect)  https://github.com/clibequilibrium/threlte/pull/1 but confirmed at https://discord.com/channels/985983540804091964/1232464795215593532/1243983366164975789

**Comment by michealparks** [comment]
Added `logarithmicDepthBuffer` support to this PR. Thanks for reporting that @clibequilibrium!

**Comment by michealparks** [comment]
> Thanks ! Could I have your opinion on something?

I'll have to think about this one. At the very it makes sense to allow the user to control whether or not the HTML is interactive.

Concerning that helper function, the requirements sound similar to what the (not yet merged) [`useViewport` hook](https://github.com/threlte/threlte/pull/951) provides. Is that hook sufficient if you were to change the target location passed to it? Or if not, can you think of what it would need to return to help you?

**Comment by clibequilibrium** [comment]
> > Thanks ! Could I have your opinion on something?
> 
> I'll have to think about this one. At the very least it makes sense to allow the user to control whether or not the HTML is interactive.
> 
> Concerning that helper function, the requirements sound similar to what the (not yet merged) [`useViewport` hook](https://github.com/threlte/threlte/pull/951) provides. Is that hook sufficient if you were to change the target location passed to it? Or if not, can you think of what it would need to return to help you?

Hi ! Sorry I did not get back to it. 

I did solve it with passing ``pointerEvents`` as well as figuring out when inputs have to be passed back to Canvas. Because just disabling pointerEvents on HTML won't enable them on canvas. 

So the solution was that :

```ts
let blockInputs = false;
// later in code 
canvas.style.pointerEvents = blockInputs ? 'auto' : 'none';
// inside useTask(
blockInputs = isMeshOccupyingScreenSpace(ref, camera.current, renderer.domElement, 0.9);
```
So technically no edits to HTML component are required because I could do that outside of the component itself.

**Comment by clibequilibrium** [comment]
FYI, having 2 HTML components one having blending occlusion and another no occlusion will force the canvas to not be occluded due to 

```ts
	if (occlude && occlude === 'blending') {
			oldZIndex = canvas.style.zIndex;
			canvas.style.zIndex = `${Math.floor(zIndexRange[0] / 2)}`;
			canvas.style.position = 'absolute';
			canvas.style.pointerEvents = $selectedEntity || blockInputs ? 'auto' : 'none';
		} else {
			canvas.style.zIndex = oldZIndex;
			canvas.style.removeProperty('position');
			canvas.style.pointerEvents = null!;
		}
```

**Comment by michealparks** [comment]
@clibequilibrium Thanks for uncovering that! Agreed that it's a bit of a code smell that HTML modifies the canvas, but I haven't yet had the time to think of a better solution there. I've added a quick fix that tracks the amount of HTML components with "occlude=blending". It should fix this issue at least.

**Comment by DefinitelyMaybe** [comment]
was looking into the `Scene.svelte` for the HTML component and noticed the old `on:event` handlers. Looked into the stackblitz package-lock.json and svelte there is `"version": "4.2.18"`. Kinda nice that it's a working example of the different svelte versions working together 😄 

I don't think we need to adjust it but what would ya'll like to do?

**Comment by grischaerbe** [comment]
Amazing work @michealparks 👍 
Before I do a review, is it expected behaviour that events pass "through" 3D objects and can then interact with HTML elements. behind them?

https://github.com/threlte/threlte/assets/46897060/52e1b097-248a-482e-8fbb-98a912ee73e4

**Comment by michealparks** [comment]
Talked on discord with the team, I'll merge this and we can follow up later with improvements. Pointer events passing through the occluding objects seem to be a limitation of the Drei component as well.

**Pull request merged**
