### PR TITLE
VolumetricSpotlight prototype

### PR DESCRIPTION
**Pull request by amr3k**
This still needs improvements that I need some help with.

- Spotlight doesn't align with the Mesh containing VolumetricSpotlight.
- Is there an easier way to apply rotation?
- The example in docs would look way better if it corresponds to pointer movement [like this](https://codesandbox.io/s/tx1pq?file=%2Fsrc%2FApp.js%3A1708-1728).

### CODE REVIEW

**Comment by amr3k** [comment]
Looks like I chose the wrong branch to merge into 😅

**Comment by grischaerbe** [comment]
Hey @amr3k, thanks so much, very much looking forward to this!
PRs are merged into the main branch. You can also change the branch to merge into of this PR.

**Comment by amr3k** [comment]
Alright, I'm going to merge `main` into `spotlight` branch just after resolving #137 . then I'll push this again into `threlte/main`

Sorry for the confusion caused by this PR

**Comment by grischaerbe** [comment]
I changed the root branch of this PR to `main` :)

**Comment by amr3k** [comment]
Thanks, I couldn't find a way to change to `main` !

Is it only allowed for maintainers?

**Comment by grischaerbe** [comment]
Hm, I don't know. Do you have this button?
Bildschirmfoto 2022-08-14 um 09 54 37

Anyways, looking forward to that one!!

**Comment by amr3k** [comment]
Yup, just found it, I swear I clicked it before many times and couldn't find the branch select menu!!
I need to get my eyes checked :P

**Comment by amr3k** [comment]
Sorry for the noise, I didn't mean to push this branch.

**Comment by grischaerbe** [comment]
Hey @amr3k! I saw your VolumetricSpotlight in action and remembered that there's a PR for that 👍 
No rush, feel free to contribute at any time!

**Pull request closed without merging**
